default_user = darkkeks
sudo = 0

project_filter = direct

# rtc_disabled = 1
qloud_disabled = 1

# deploy_project_id = 169
# deploy_dc = sas
# deploy_dc = vla
# deploy_dc = man
# deploy_dc = iva
# deploy_dc = myt
