set-option -s default-terminal screen-256color

set -g prefix C-a
bind C-a send-prefix
unbind C-b

set -g base-index 1

set -s escape-time 0

set -g mouse on

set-option -gw window-status-current-style bg=red

set -g status-position top
