# Tmux uses "screen" by default, which only supports 8 colors
set-option -s default-terminal screen-256color

# Start enumerating windows with 1
set -g base-index 1

# Non-zero escape-time makes escape input delayed
set -s escape-time 0

# Enable mouse
set -g mouse on

# Highlight current window in red
set-option -gw window-status-current-style bg=red

# Increase history limit
set-option -g history-limit 100000
